site_name: BLIPSS Tutorial
theme:
  name: 'material'
nav:
  - Introduction: index.md
  - Getting Started: getting_started.md
  - Data Preparation: data_preparation.md
  - Running BLIPSS: running_blipss.md
  - Interpreting Results: interpreting_results.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
